# Generated by Django 3.1.3 on 2021-01-05 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_description_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='description_header',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
